#######################################################
# 
# HamburgStore.py
# Python implementation of the Class HamburgStore
# Generated by Enterprise Architect
# Created on:      19-6��-2021 15:37:37
# Original author: 70748
# 
#######################################################

from .Hamburg import Hamburg
from .SimpleFactory import SimpleFactory
class HamburgStore:
    def orderHamburg(self, type:str)->Hamburg:
        """点单一个汉堡
        type: 汉堡类型
        """
        hamburg: Hamburg = SimpleFactory.getHamburg(type)
        if hamburg != None:
            hamburg.ready()
            hamburg.cook()
            hamburg.box()
        return hamburg
