#######################################################
#
# MiDeskLampOffCommand.py
# Python implementation of the Class MiDeskLampOffCommand
# Generated by Enterprise Architect
# Created on:      29-6��-2021 11:26:32
# Original author: 70748
#
#######################################################
from smart_home_v2.src.MiDeskLamp import MiDeskLamp
from smart_home_v2.src.commnad.Command import Command


class MiDeskLampOffCommand(Command):
    def __init__(self, miDeskLamp: MiDeskLamp) -> None:
        super().__init__()
        self._miDeskLamp = miDeskLamp

    def execute(self):
        self._miDeskLamp.setBrightness(0)
