#######################################################
# 
# NormalDeskLampOffCommnad.py
# Python implementation of the Class NormalDeskLampOffCommnad
# Generated by Enterprise Architect
# Created on:      29-6��-2021 11:26:32
# Original author: 70748
# 
#######################################################
from smart_home_v2.src.NormalDeskLamp import NormalDeskLamp
from smart_home_v2.src.commnad.Command import Command

class NormalDeskLampOffCommnad(Command):
    def __init__(self, normalDeskLamp: NormalDeskLamp) -> None:
        super().__init__()
        self._normalDeskLamp = normalDeskLamp

    def execute(self):
        self._normalDeskLamp.off()