#######################################################
# 
# CarrierAdapter.py
# Python implementation of the Class CarrierAdapter
# Generated by Enterprise Architect
# Created on:      30-6��-2021 15:38:36
# Original author: 70748
# 
#######################################################
from carrier_v1.src.Cruiser import Cruiser
from carrier_v1.src.Carrier import Carrier

class CarrierAdapter(Carrier):
    def __init__(self, cruiser: Cruiser) -> None:
        super().__init__()
        self.__cruiser = cruiser

    def recoveryAircraft(self):
        print("{!s} recovering aircraft".format(self.__cruiser))

    def takeOffAircraft(self):
        print("{!s} taking off aircraft".format(self.__cruiser))