#######################################################
#
# Cruiser.py
# Python implementation of the Class Cruiser
# Generated by Enterprise Architect
# Created on:      30-6��-2021 15:38:36
# Original author: 70748
#
#######################################################
import abc


class Cruiser(abc.ABC):
    @abc.abstractmethod
    def gunFire(self):
        pass
