#######################################################
#
# BeijingIngredientFactory.py
# Python implementation of the Class BeijingIngredientFactory
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
#
#######################################################
from .IngredientsFactory import IngredientsFactory
from .BeijingPepper import BeijingPepper
from .WhiteFeatherChicken import WhiteFeatherChicken
from .Chicken import Chicken
from .Pepper import Pepper


class BeijingIngredientFactory(IngredientsFactory):
    def getChicken(self) -> Chicken:
        return WhiteFeatherChicken()

    def getPepper(self) -> Pepper:
        return BeijingPepper()
