#######################################################
#
# BeijingHamburgStore.py
# Python implementation of the Class BeijingHamburgStore
# Generated by Enterprise Architect
# Created on:      19-6��-2021 18:39:44
# Original author: 70748
#
#######################################################
from .HamburgStore import HamburgStore
from .ZingerBurger import ZingerBurger
from .MiniBurger import MiniBurger
from .NewOrleansRoastedBurger import NewOrleansRoastedBurger
from .Hamburg import Hamburg
from .BeijingIngredientFactory import BeijingIngredientFactory


class BeijingHamburgStore(HamburgStore):
    def creatHamburg(self, type: str) -> Hamburg:
        hamburg: Hamburg = None
        factory = BeijingIngredientFactory()
        if type == "zinger":
            hamburg = ZingerBurger(factory)
        elif type == "new_orliean":
            hamburg = NewOrleansRoastedBurger(factory)
        elif type == "mini":
            hamburg = MiniBurger(factory)
        else:
            pass
        return hamburg
