#######################################################
# 
# BlackChicken.py
# Python implementation of the Class BlackChicken
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
# 
#######################################################
from .Chicken import Chicken

class BlackChicken(Chicken):
    pass