#######################################################
# 
# Chicken.py
# Python implementation of the Class Chicken
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
# 
#######################################################

import abc
class Chicken(abc.ABC):
    pass