#######################################################
#
# IngredientsFactory.py
# Python implementation of the Class IngredientsFactory
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
#
#######################################################

import abc
from .Chicken import Chicken
from .Pepper import Pepper


class IngredientsFactory(abc.ABC):
    @abc.abstractmethod
    def getChicken(self) -> Chicken:
        pass

    @abc.abstractmethod
    def getPepper(self) -> Pepper:
        pass
