#######################################################
#
# JiangSuHamburgStore.py
# Python implementation of the Class JiangSuHamburgStore
# Generated by Enterprise Architect
# Created on:      19-6��-2021 18:39:45
# Original author: 70748
#
#######################################################
from .JiangsuIngredientsFactory import JiangsuIngredientsFactory
from .Hamburg import Hamburg
from .HamburgStore import HamburgStore
from .NotHotMiniBurger import NotHotMiniBurger
from .NotHotNewOrleansRoastedBurger import NotHotNewOrleansRoastedBurger
from .NotHotZingerBurger import NotHotZingerBurger


class JiangSuHamburgStore(HamburgStore):
    def creatHamburg(self, type: str) -> Hamburg:
        hamburg: Hamburg = None
        factory = JiangsuIngredientsFactory()
        if type == "zinger":
            hamburg = NotHotZingerBurger(factory)
        elif type == "new_orliean":
            hamburg = NotHotNewOrleansRoastedBurger(factory)
        elif type == "mini":
            hamburg = NotHotMiniBurger(factory)
        else:
            pass
        return hamburg
