#######################################################
#
# JiangsuIngredientsFactory.py
# Python implementation of the Class JiangsuIngredientsFactory
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
#
#######################################################
from .IngredientsFactory import IngredientsFactory
from .Pepper import Pepper
from .Chicken import Chicken
from .JiangsuPepper import JiangsuPepper
from .BlackChicken import BlackChicken


class JiangsuIngredientsFactory(IngredientsFactory):
    def getChicken(self) -> Chicken:
        return BlackChicken()

    def getPepper(self) -> Pepper:
        return JiangsuPepper()
