#######################################################
# 
# Pepper.py
# Python implementation of the Class Pepper
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
# 
#######################################################

import abc
class Pepper(abc.ABC):
    pass