#######################################################
# 
# SichuanPepper.py
# Python implementation of the Class SichuanPepper
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
# 
#######################################################
from .Pepper import Pepper

class SichuanPepper(Pepper):
    pass