#######################################################
#
# SichuanIngredientsFactory.py
# Python implementation of the Class SichuanIngredientsFactory
# Generated by Enterprise Architect
# Created on:      19-6��-2021 21:34:31
# Original author: 70748
#
#######################################################
from .Chicken import Chicken
from .Pepper import Pepper
from .SichuanPepper import SichuanPepper
from .ThreeYellowChicken import ThreeYellowChicken
from .IngredientsFactory import IngredientsFactory


class SichuanIngredientsFactory(IngredientsFactory):
    def getChicken(self) -> Chicken:
        return ThreeYellowChicken()

    def getPepper(self) -> Pepper:
        return SichuanPepper()
