#######################################################
#
# MiDeskLamp.py
# Python implementation of the Class MiDeskLamp
# Generated by Enterprise Architect
# Created on:      28-6��-2021 18:03:34
# Original author: 70748
#
#######################################################


class MiDeskLamp:
    def setBrightness(self, brightness: int):
        print("now mi desk lamp's brightness is {}".format(brightness))
