#######################################################
#
# MiDestkLampButton.py
# Python implementation of the Class MiDestkLampButton
# Generated by Enterprise Architect
# Created on:      28-6��-2021 18:03:34
# Original author: 70748
#
#######################################################
from smart_home_v1.src.MiDeskLamp import MiDeskLamp
from smart_home_v1.src.ControlButton import ControlButton


class MiDestkLampButton(ControlButton):
    def __init__(self, deskLamp: MiDeskLamp) -> None:
        super().__init__()
        self.deskLamp = deskLamp

    def off(self):
        self.deskLamp.setBrightness(0)

    def on(self):
        self.deskLamp.setBrightness(50)
