#######################################################
# 
# NormalDeskLamp.py
# Python implementation of the Class NormalDeskLamp
# Generated by Enterprise Architect
# Created on:      28-6��-2021 18:03:34
# Original author: 70748
# 
#######################################################


class NormalDeskLamp:
    def off(self):
        print("now normall desk lamp is turn off")

    def on(self):
        print("now normall desk lamp is turn on")