#######################################################
#
# NormalDeskLampButton.py
# Python implementation of the Class NormalDeskLampButton
# Generated by Enterprise Architect
# Created on:      28-6��-2021 18:03:34
# Original author: 70748
#
#######################################################
from smart_home_v1.src.NormalDeskLamp import NormalDeskLamp
from smart_home_v1.src.ControlButton import ControlButton


class NormalDeskLampButton(ControlButton):
    def __init__(self, deskLamp: NormalDeskLamp) -> None:
        super().__init__()
        self.deskLamp: NormalDeskLamp = deskLamp

    def off(self):
        self.deskLamp.off()

    def on(self):
        self.deskLamp.on()
