#######################################################
#
# TV.py
# Python implementation of the Interface TV
# Generated by Enterprise Architect
# Created on:      20-7��-2021 14:11:12
# Original author: 70748
#
#######################################################
from abc import ABC, abstractmethod


class TV(ABC):
    @abstractmethod
    def getChannelTotal(self):
        pass

    @abstractmethod
    def setChannel(self, number):
        pass

    @abstractmethod
    def on(self):
        pass

    @abstractmethod
    def off(self):
        pass
