#######################################################
#
# WeatherSDK.py
# Python implementation of the Class WeatherSDK
# Generated by Enterprise Architect
# Created on:      13-6��-2021 18:19:09
# Original author: 70748
#
#######################################################
from typing import List
from .air_quality import AirQuality


class WeatherSDK():
    def __init__(self) -> None:
        super().__init__()
        self.observers: List["Observer"] = []
        self.temperature: float = 0
        self.humidity: float = 0
        self.airQuality: AirQuality = AirQuality.NORMAL

    def changeWeatherInfo(self, temperature: float, humidity: float, airQuality: AirQuality) -> None:
        self.temperature = temperature
        self.humidity = humidity
        self.airQuality = airQuality
        self.notifyObservers()

    def deleteObserver(self, observer: "Observer"):
        self.observers.remove(observer)

    def notifyObservers(self):
        for observer in self.observers:
            observer.update()

    def registeObserver(self, observer: "Observer"):
        self.observers.append(observer)
