#######################################################
#
# BeijingHamburgStore.py
# Python implementation of the Class BeijingHamburgStore
# Generated by Enterprise Architect
# Created on:      19-6��-2021 18:39:44
# Original author: 70748
#
#######################################################
from .HamburgStore import HamburgStore
from .ZingerBurger import ZingerBurger
from .MiniBurger import MiniBurger
from .NewOrleansRoastedBurger import NewOrleansRoastedBurger
from .Hamburg import Hamburg


class BeijingHamburgStore(HamburgStore):
    def creatHamburg(self, type: str) -> Hamburg:
        hamburg: Hamburg = None
        if type == "zinger":
            hamburg = ZingerBurger()
        elif type == "new_orliean":
            hamburg = NewOrleansRoastedBurger()
        elif type == "mini":
            hamburg = MiniBurger()
        else:
            pass
        return hamburg
