#######################################################
#
# SichuanHamburgStore.py
# Python implementation of the Class SichuanHamburgStore
# Generated by Enterprise Architect
# Created on:      19-6��-2021 18:39:45
# Original author: 70748
#
#######################################################
from .Hamburg import Hamburg
from .HamburgStore import HamburgStore
from .VeryHotMiniBurger import VeryHotMiniBurger
from .VeryHotNewOrleansRoastedBurger import VeryHotNewOrleansRoastedBurger
from .VeryHotZingerBurger import VeryHotZingerBurger


class SichuanHamburgStore(HamburgStore):
    def creatHamburg(self, type: str) -> Hamburg:
        hamburg: Hamburg = None
        if type == "zinger":
            hamburg = VeryHotZingerBurger()
        elif type == "new_orliean":
            hamburg = VeryHotNewOrleansRoastedBurger()
        elif type == "mini":
            hamburg = VeryHotMiniBurger()
        else:
            pass
        return hamburg
