#######################################################
#
# ButtonStatus.py
# Python implementation of the Class ButtonStatus
# Generated by Enterprise Architect
# Created on:      29-6��-2021 11:26:32
# Original author: 70748
#
#######################################################
from enum import Enum


class ButtonStatus(Enum):
    ON = 1
    OFF = 2
