#######################################################
# 
# NormalDeskLamp.py
# Python implementation of the Class NormalDeskLamp
# Generated by Enterprise Architect
# Created on:      29-6��-2021 11:26:32
# Original author: 70748
# 
#######################################################


class NormalDeskLamp:
    def off(self):
        print("normal desk lamp is turn off")

    def on(self):
        print("normal desk lamp is turn on")