#######################################################
# 
# WeatherAPP3.py
# Python implementation of the Class WeatherAPP3
# Generated by Enterprise Architect
# Created on:      13-6��-2021 18:19:09
# Original author: 70748
# 
#######################################################
from .WeatherSDK import WeatherSDK
from .Observer import Observer
from .Display import Display
from .Subject import Subject
from .air_quality import AirQuality,show_air_quality_text

class WeatherAPP3(Observer, Display):
    def __init__(self) -> None:
        super().__init__()
        self.airQuality: AirQuality = AirQuality.NORMAL


    def display(self):
        '''显示天气信息'''
        print("="*10)
        print("天气APP3")
        print("现在的空气质量{}".format(show_air_quality_text(self.airQuality)))
        sportsHint: str = ""
        if self.airQuality in (AirQuality.HEAVEY_POLLUTED, AirQuality.LIGHTLY_POLLUTED):
            sportsHint = "空气质量不好，建议宅家"
        else:
            sportsHint = "空气不错，出去运动一下吧"
        print("运动建议：{}".format(sportsHint))
        print("="*10)

    def update(self, subject:Subject):
        if isinstance(subject, WeatherSDK):
            sdk: WeatherSDK = subject
            self.airQuality = sdk.airQuality
            self.display()