#######################################################
#
# Kodi.py
# Python implementation of the Class Kodi
# Generated by Enterprise Architect
# Created on:      01-7��-2021 11:07:50
# Original author: 70748
#
#######################################################
from simple_smart_home.src.Service import Service


class Kodi(Service):
    def playFavorateMovie(self):
        print("starting play your favorate movie")

    def restart(self):
        print("{!s} restart".format(self))

    def shutdown(self):
        print("{!s} shutdown".format(self))

    def start(self):
        print("{!s} start".format(self))

    def __str__(self) -> str:
        return self.__class__.__name__
