#######################################################
#
# Light.py
# Python implementation of the Class Light
# Generated by Enterprise Architect
# Created on:      01-7��-2021 11:07:50
# Original author: 70748
#
#######################################################


class Light:
    def setLightness(self, lightness):
        print("now light's lightness is {}".format(lightness))
