#######################################################
#
# Service.py
# Python implementation of the Class Service
# Generated by Enterprise Architect
# Created on:      01-7��-2021 11:07:50
# Original author: 70748
#
#######################################################
from abc import ABC, abstractmethod


class Service(ABC):
    @abstractmethod
    def restart():
        pass

    @abstractmethod
    def shutdown():
        pass

    @abstractmethod
    def start():
        pass
