#######################################################
# 
# SimpleSmartHome.py
# Python implementation of the Class SimpleSmartHome
# Generated by Enterprise Architect
# Created on:      01-7��-2021 11:07:50
# Original author: 70748
# 
#######################################################
from simple_smart_home.src.AirConditioner import AirConditioner
from .Light import Light
from .SmartTV import SmartTV
from .Raspberry import Raspberry

class SimpleSmartHome:
    def watchMovie(self):
        conditioner = AirConditioner()
        conditioner.on()
        conditioner.setTemprature(18)
        ligt = Light()
        ligt.setLightness(10)
        tv = SmartTV()
        tv.on()
        rasp = Raspberry()
        rasp.start()
        rasp.startService("Kodi")
        rasp.exec("Kodi", "playFavorateMovie")