#######################################################
#
# Command.py
# Python implementation of the Class Command
# Generated by Enterprise Architect
# Created on:      29-6��-2021 11:26:32
# Original author: 70748
#
#######################################################
from abc import ABC, abstractmethod


class Command(ABC):
    @abstractmethod
    def execute(self) -> None:
        pass

    @abstractmethod
    def undo(self) -> None:
        pass
