#######################################################
#
# Display.py
# Python implementation of the Interface Display
# Generated by Enterprise Architect
# Created on:      13-6��-2021 18:19:09
# Original author: 70748
#
#######################################################
from abc import ABC, abstractmethod


class Display(ABC):
    @abstractmethod
    def display(self):
        pass
