#######################################################
#
# Observer.py
# Python implementation of the Interface Observer
# Generated by Enterprise Architect
# Created on:      13-6��-2021 18:19:09
# Original author: 70748
#
#######################################################
from abc import ABC, abstractmethod
from .Subject import Subject


class Observer(ABC):
    @abstractmethod
    def update(self):
        pass
