#######################################################
#
# Subject.py
# Python implementation of the Interface Subject
# Generated by Enterprise Architect
# Created on:      13-6��-2021 18:19:09
# Original author: 70748
#
#######################################################
# from .Observer import Observer
from abc import ABC, abstractmethod


class Subject(ABC):
    @abstractmethod
    def deleteObserver(self, observer: "Observer"):
        pass

    @abstractmethod
    def notifyObservers(self):
        pass

    @abstractmethod
    def registeObserver(self, observer: "Observer"):
        pass
