#######################################################
#
# MiDeskLamp.py
# Python implementation of the Class MiDeskLamp
# Generated by Enterprise Architect
# Created on:      29-6��-2021 11:26:32
# Original author: 70748
#
#######################################################


class MiDeskLamp:
    def setBrightness(self, brightness: int):
        print("now mi desk lamp's brightness is {}".format(brightness))
