#######################################################
#
# JiangSuHamburgStore.py
# Python implementation of the Class JiangSuHamburgStore
# Generated by Enterprise Architect
# Created on:      19-6��-2021 18:39:45
# Original author: 70748
#
#######################################################
from .Hamburg import Hamburg
from .HamburgStore import HamburgStore
from .NotHotMiniBurger import NotHotMiniBurger
from .NotHotNewOrleansRoastedBurger import NotHotNewOrleansRoastedBurger
from .NotHotZingerBurger import NotHotZingerBurger


class JiangSuHamburgStore(HamburgStore):
    def orderHamburg(self, type: str) -> Hamburg:
        hamburg: Hamburg = None
        if type == "zinger":
            hamburg = NotHotZingerBurger()
        elif type == "new_orliean":
            hamburg = NotHotNewOrleansRoastedBurger()
        elif type == "mini":
            hamburg = NotHotMiniBurger()
        else:
            pass
        if hamburg != None:
            hamburg.ready()
            hamburg.cook()
            hamburg.box()
        return hamburg
