#######################################################
#
# NotHotMiniBurger.py
# Python implementation of the Class NotHotMiniBurger
# Generated by Enterprise Architect
# Created on:      19-6��-2021 18:39:45
# Original author: 70748
#
#######################################################
from .Hamburg import Hamburg


class NotHotMiniBurger(Hamburg):
    def __init__(self) -> None:
        super().__init__("Mini Hamburger")


    def box(self):
        print("box {}".format(self.name))

    def cook(self):
        print("cook {}".format(self.name))

    def ready(self):
        print("Prepare ingredients")
