#######################################################
# 
# Client.py
# Python implementation of the Class Client
# Generated by Enterprise Architect
# Created on:      20-7ÔÂ-2021 15:54:03
# Original author: 70748
# 
#######################################################


class Client:
    pass