#######################################################
#
# TripBuilderInterface.py
# Python implementation of the Interface TripBuilderInterface
# Generated by Enterprise Architect
# Created on:      20-7��-2021 15:54:03
# Original author: 70748
#
#######################################################
from abc import ABC, abstractmethod


class TripBuilderInterface(ABC):
    @abstractmethod
    def addHotel(self, time, hotel):
        pass

    @abstractmethod
    def addRestaurant(self, time, restaurant):
        pass

    @abstractmethod
    def addTicket(self, time, ticket):
        pass

    @abstractmethod
    def buildDay(self):
        pass

    @abstractmethod
    def getTrip(self):
        pass
