#######################################################
#
# Trip.py
# Python implementation of the Class Trip
# Generated by Enterprise Architect
# Created on:      20-7��-2021 15:54:03
# Original author: 70748
#
#######################################################


from .Day import Day


class Trip:
    def __init__(self) -> None:
        self._days = []

    def addDay(self, day: Day):
        self._days.append(day)

    def print(self):
        day: Day
        num: int = 1
        for day in self._days:
            print("第{}天：".format(num))
            day.print()
            num += 1
