#######################################################
#
# TripBuilder.py
# Python implementation of the Class TripBuilder
# Generated by Enterprise Architect
# Created on:      20-7��-2021 15:54:03
# Original author: 70748
#
#######################################################
from .Restaurant import Restaurant
from .Hotel import Hotel
from .Day import Day
from .Trip import Trip
from .TripBuilderInterface import TripBuilderInterface
from .Ticket import Ticket


class TripBuilder(TripBuilderInterface):
    def __init__(self) -> None:
        super().__init__()
        self._currentDay: Day = None
        self._trip: Trip = Trip()

    def addHotel(self, time: str, hotel: Hotel):
        self._currentDay.addTripItem(time, hotel)

    def addRestaurant(self, time: str, restaurant: Restaurant):
        self._currentDay.addTripItem(time, restaurant)

    def addTicket(self, time: str, ticket: Ticket):
        self._currentDay.addTripItem(time, ticket)

    def buildDay(self):
        self._currentDay = Day()
        self._trip.addDay(self._currentDay)

    def getTrip(self)->Trip:
        return self._trip

    def print(self):
        self._trip.print()
