#######################################################
#
# File.py
# Python implementation of the Class File
# Generated by Enterprise Architect
# Created on:      20-7��-2021 17:46:52
# Original author: 70748
#
#######################################################


class File:
    def __init__(self, path: str) -> None:
        self._path: str = path
        _, _, ext = self._path.rpartition('.')
        self._ext = ext

    def getExt(self) -> str:
        return self._ext

    def __str__(self) -> str:
        return self._path
