#######################################################
#
# FileClassCollection.py
# Python implementation of the Class FileClassCollection
# Generated by Enterprise Architect
# Created on:      20-7��-2021 17:46:52
# Original author: 70748
#
#######################################################
from .File import File
from .FileClass import FileClass


class FileClassCollection:
    def __init__(self) -> None:
        self._fileClasses: dict[FileClass:list] = dict()

    def addFile(self, file: File, fileClass: FileClass):
        if fileClass not in self._fileClasses:
            self._fileClasses[fileClass] = []
        self._fileClasses[fileClass].append(file)

    def print(self):
        for fileClass, files in self._fileClasses.items():
            print(fileClass)
            num = 0
            for file in files:
                print(file)
                num += 1
                if num > 10:
                    print("...")
                    break
