#######################################################
#
# VedioClassify.py
# Python implementation of the Class VedioClassify
# Generated by Enterprise Architect
# Created on:      20-7��-2021 17:46:52
# Original author: 70748
#
#######################################################
from .FileClass import FileClass
from .FileClassCollection import FileClassCollection
from .File import File
from .FileClassify import FileClassify


class VedioClassify(FileClassify):
    def classify(self, file: File, fileCollection: FileClassCollection) -> bool:
        if file.getExt() in {"mp4", "kmv"}:
            fileCollection.addFile(file, FileClass.VEDIO)
            return True
        return False
