#######################################################
# 
# ExtraArmour.py
# Python implementation of the Class ExtraArmour
# Generated by Enterprise Architect
# Created on:      15-6��-2021 14:00:36
# Original author: 70748
# 
#######################################################
from .ExtraEquipment import ExtraEquipment
from .Tank import Tank

class ExtraArmour(ExtraEquipment):
    def __init__(self, tank: Tank):
        super().__init__(tank)
        self.price = 10000
        self.des = "附加装甲"
        
