#######################################################
#
# ExtraEquipment.py
# Python implementation of the Class ExtraEquipment
# Generated by Enterprise Architect
# Created on:      15-6��-2021 14:00:36
# Original author: 70748
#
#######################################################
from .Tank import Tank
import abc


class ExtraEquipment(Tank, abc.ABC):
    def __init__(self, tank: Tank):
        self.tank: Tank = tank
        self.price: int = 0
        self.des: str = ""

    def cost(self):
        return self.price + self.tank.cost()

    def getDescription(self):
        return self.tank.getDescription()+','+self.des
