#######################################################
#
# TankBody.py
# Python implementation of the Class TankBody
# Generated by Enterprise Architect
# Created on:      15-6��-2021 14:00:36
# Original author: 70748
#
#######################################################
from .Tank import Tank
import abc


class TankBody(Tank, abc.ABC):
    def __init__(self) -> None:
        super().__init__()
        self.des: str = ""
        self.price: int = 0

    def cost(self):
        return self.price

    def getDescription(self):
        return self.des
